### ISSUE TITLE
大佬你好，我们能交流下写GUI的经验吗？

### ISSUE THREAD

**Issue by user1121114685** [getbuguai/gaihosts#1]
打扰了

**Comment by user1121114685** [comment]
我想做一个文件选择的按钮。只需要获取到文件路径即可。

**Comment by zangdale** [comment]
fyne官方库 的 cmd文件夹，中的fyne_demo，中有打开一个文件夹和文件的例子，你可以本地运行找找里面的代码，我也是新手，也是看到了gui库就试试看。
